### ISSUE TITLE
"Type" of Business - 

### ISSUE THREAD

**Issue by sharpasabubble** [j26design/Local-SEO-Premium#2]
There are no categories for Assisted Living, Senior Services, Memory Care Facility (and there many, many, many businesses that cater to the elderly!)

**Comment by jp26jp** [comment]
Those all fall under the [medical business types](http://health-lifesci.schema.org/MedicalBusiness). There are 24 medical business types. You can't just put whatever value you want.

**Comment by sharpasabubble** [comment]
I appreciate the speedy response and suggestion, however, Assisted Living is not a medical service.

**Comment by jp26jp** [comment]
Yes it is.
