### ISSUE TITLE
SEO Premium

### ISSUE THREAD

**Issue by cutler1** [j26design/Local-SEO-Premium#3]
Hello:

Would it be possible to add an option for country in the address section?  

Thanks,
Edward

**Comment by jp26jp** [comment]
Yep! I just added the feature so if you're a Lifetime member then the widget has synced to your computer! If not, I will try to get the update sent out in the next few days.

**Comment by cutler1** [comment]
Thanks for the update!  Unfortunately I didn't see an option to get a lifetime membership on the Local SEO Premium page so I just purchased the widget separately. If I purchase a lifetime membership, will I get the updated widjet today?

**Comment by jp26jp** [comment]
An update with this feature was just sent out!
