### ISSUE TITLE
Country name in locations not correct

### ISSUE THREAD

**Issue by john-klungers** [j26design/Local-SEO-Premium#5]
In location I choose from the list South Africa. in the name US appears 
![schermafbeelding 2017-08-11 om 12 51 52](https://user-images.githubusercontent.com/904476/29210530-529cf93e-7e94-11e7-80bf-237f398273fc.png)

**Comment by jp26jp** [comment]
Oh weird. I'll release an update that fixes this issue.

**Comment by jp26jp** [comment]
The update was just sent out!
